### ISSUE TITLE
outated Bindings For Python 3 - swig 4 update needed

### ISSUE THREAD

**Issue by chetanjain2099** [portaloffreedom/polyvox#1] opened 2020-05-08 09:43 UTC
I am having issues with building PolyVox for Python3. Could anyone help with the compilation of this library for Python3.

>>> import PolyVoxCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chetan\Documents\Zephyr3\Python37\setup\Modules\New\git\po\polyvox\build\bindings\PolyVoxCore.py", line 146, in <module>
    class Vector3Dfloat(object):
  File "C:\Users\Chetan\Documents\Zephyr3\Python37\setup\Modules\New\git\po\polyvox\build\bindings\PolyVoxCore.py", line 258, in Vector3Dfloat
    __swig_getmethods__["x"] = getX
NameError: name '__swig_getmethods__' is not defined

**Comment by portaloffreedom** [comment] 2020-05-11 17:01
I just checked and I can replicate the same error.
I definetely managed to build this with python3 bindings, but it was ages ago and I don't remember any more...
let me see, I think it's just a stupid error that I can quickly fix

**Comment by portaloffreedom** [comment] 2020-05-11 17:04
Nevermind, the issue seems to be deeper.
According to a quick google search I made the problem is that they removed the `swig_getmethods` from swig 4.0 and probably some files needs to be updated to make it work again.

**Comment by portaloffreedom** [comment] 2020-05-11 17:30
Fixed with commit e7e1d30052bab161b24f8a5f532232ef7cdfd22e

@chetanjain2099 try to have a look now if it works for you

**Closed as completed** 2020-05-13 13:57 UTC

**Comment by chetanjain2099** [comment] 2020-05-13 14:00
> Fixed with commit [e7e1d30](https://github.com/portaloffreedom/polyvox/commit/e7e1d30052bab161b24f8a5f532232ef7cdfd22e)
> 
> @chetanjain2099 try to have a look now if it works for you

Thanks. I will have a look.

**Comment by chetanjain2099** [comment] 2020-05-15 02:50
> Fixed with commit [e7e1d30](https://github.com/portaloffreedom/polyvox/commit/e7e1d30052bab161b24f8a5f532232ef7cdfd22e)
> 
> @chetanjain2099 try to have a look now if it works for you

I was able to compile the library but then I wanted to test the example given in this library. I got this error:

Traceback (most recent call last):
  File "PythonExample.py", line 34, in <module>
    vol = pv.SimpleVolumeuint8(r)
AttributeError: module 'PolyVoxCore' has no attribute 'SimpleVolumeuint8'

and this also:

AttributeError: module 'PolyVoxCore' has no attribute 'CubicSurfaceExtractorWithNormalsSimpleVolumeuint8'

Can you suggest me how do I fix this?
